N_FRAMES = 100
BATCH_SIZE = 10


DATA_FOLDER_BASE = "/data/"

SPLITS_FOLDER = DATA_FOLDER_BASE + "utils/splits/"
METADATA_FILE = DATA_FOLDER_BASE + "utils/metadata.csv"
FACES_COORDINATES = DATA_FOLDER_BASE + "utils/faces_coordinates.npy"

RAW_DATA_FOLDER_REAL = "{}face_forensics/original_sequences/".format(DATA_FOLDER_BASE)
RAW_DATA_FOLDER_FAKES = "{}face_forensics/manipulated_sequences/".format(DATA_FOLDER_BASE)


PROCESSED_FACES_MARGIN_0 = DATA_FOLDER_BASE + "processed_0/"
PROCESSED_FACES_MARGIN_10 = DATA_FOLDER_BASE + "processed_10/"
PROCESSED_FACES_MARGIN_30 = DATA_FOLDER_BASE + "processed_30/"
PROCESSED_FACES_MARGIN_50 = DATA_FOLDER_BASE + "processed_50/"
PROCESSED_DATA_FOLDER = {0: PROCESSED_FACES_MARGIN_0, 10:PROCESSED_FACES_MARGIN_10, 30:PROCESSED_FACES_MARGIN_30, 50:PROCESSED_FACES_MARGIN_50}


MODELS_FOLDER = DATA_FOLDER_BASE + "models/"


RESULTS_FILE = DATA_FOLDER_BASE + "results.csv"


FF_BENCHMARK_IMAGES_FOLDER = DATA_FOLDER_BASE + "faceforensics_benchmark_images"